### ISSUE TITLE
Example app not working?

### ISSUE THREAD

**Issue by adityadivekar03** [narenchoudhary/django-iitg-auth#4]
Could you confirm if the example app is working?
Reproduce -
```
git clone https://github.com/narenchoudhary/django-iitg-auth.git
python setup.py install
cd example/
python manage.py migrate
python manage.py runserver
```
The login does not work, and an error `No user found for given credentials.` is produced for correct credentials

**Comment by narenchoudhary** [comment]
This error comes from `WebMailAuthenticationBackend.authenticate` method in `auth.py` file.   https://github.com/narenchoudhary/django-iitg-auth/blob/3cdc88b00931ed29d124e5f302035420cd8de90a/iitgauth/auth.py#L55

This basically means application is unable to open a POP3 connection with IITG webmail servers. 

I need answers for following questions:  
* Which login server are you using? 
* Has IITG added new login servers which do not appear in `LOGIN_SERVERS` ? (See below for link) 
* Maybe they've moved existing servers to new IPs? 
* Have they changed the POP3 port? 

I'm not in campus so I'll need some of this info from you.

 https://github.com/narenchoudhary/django-iitg-auth/blob/3cdc88b00931ed29d124e5f302035420cd8de90a/iitgauth/constants.py#L1

**Comment by narenchoudhary** [comment]
:wave:  @kmskrishna can you help with the questions?

**Comment by kmskrishna** [comment]
Nothing changed and POPlib is working fine.

**Comment by narenchoudhary** [comment]
@adityadivekar03 

~It is a Django2.0 issue. I'll push the update over the weekend. Can you try with Django<=1.10.5 ?~

It wasn't a Django2.0 issue. You probably were doing something wrong. Anyways, I've separated example project into a new repository. It is now available here: https://github.com/narenchoudhary/django-iitg-auth-example.
